// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHO75Gd0v6EHzNsaPBaG3QIvMJ-pPZnxU',
    appId: '1:965765655548:web:62746c187dc8fba2da2079',
    messagingSenderId: '965765655548',
    projectId: 'iot-project-5047c',
    authDomain: 'iot-project-5047c.firebaseapp.com',
    databaseURL: 'https://iot-project-5047c-default-rtdb.firebaseio.com',
    storageBucket: 'iot-project-5047c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbfJNY3fWXpn8Ex9pAOumDLWIYpBJRTWM',
    appId: '1:965765655548:android:a1301e3d6d3ea24fda2079',
    messagingSenderId: '965765655548',
    projectId: 'iot-project-5047c',
    databaseURL: 'https://iot-project-5047c-default-rtdb.firebaseio.com',
    storageBucket: 'iot-project-5047c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJoj81drp7M_K09yUJwwOBY1E454WR1R8',
    appId: '1:965765655548:ios:5aef382f1717f2aada2079',
    messagingSenderId: '965765655548',
    projectId: 'iot-project-5047c',
    databaseURL: 'https://iot-project-5047c-default-rtdb.firebaseio.com',
    storageBucket: 'iot-project-5047c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJoj81drp7M_K09yUJwwOBY1E454WR1R8',
    appId: '1:965765655548:ios:5aef382f1717f2aada2079',
    messagingSenderId: '965765655548',
    projectId: 'iot-project-5047c',
    databaseURL: 'https://iot-project-5047c-default-rtdb.firebaseio.com',
    storageBucket: 'iot-project-5047c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHO75Gd0v6EHzNsaPBaG3QIvMJ-pPZnxU',
    appId: '1:965765655548:web:de8de2cfd7d9a517da2079',
    messagingSenderId: '965765655548',
    projectId: 'iot-project-5047c',
    authDomain: 'iot-project-5047c.firebaseapp.com',
    databaseURL: 'https://iot-project-5047c-default-rtdb.firebaseio.com',
    storageBucket: 'iot-project-5047c.firebasestorage.app',
  );
}
